apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
  labels: 
    name:  demo
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo 
        image: chinmaytechp/demoapp:v1
        ports:
          - containerPort: 8090